#include "../webserv.hpp"

/* --------------------------------------------------------------------------------
Return the path to the executable in which to run the script, depending on
whether the file extension is .py (Python) or .pl (Perl)
Return an empty string if the extension is different
-------------------------------------------------------------------------------- */
std::string file_extention(std::string filePath)
{
	size_t i = 0;

	while (filePath[i++]);
	while (i && filePath[--i] != '.');

	std::cout << colors::bright_magenta << "file_extension: " << colors::reset << &filePath[i] << std::endl;
	// return ((!strcmp(&filePath[i], ".py")) ? "/usr/bin/python3" : ((!strcmp(&filePath[i], ".pl")) ? "/usr/bin/perl" : ""));
	if (!strcmp(&filePath[i], ".py"))
		return "/usr/bin/python2.7";
	else if (!strcmp(&filePath[i], ".pl"))
		return "/usr/bin/perl";
	else if (!strcmp(&filePath[i], ".php"))
		return "/usr/bin/php";
	else
		return "";
}

/* --------------------------------------------------------------------------------
Check if the executable can be launched with the received path
Return the path to the executable if it works, otherwise an empty string
-------------------------------------------------------------------------------- */
std::string search_exec(std::string filePath)
{
	const std::string exec = file_extention(filePath);

	if (exec == "")
	{
		std::cerr << "incompatible CGI-script" << std::endl;
		return ("");
	}
	return ((!access(exec.c_str(), X_OK)) ? exec : "");
}

/* --------------------------------------------------------------------------------
Converts a size_t numeric value to std::string.
-------------------------------------------------------------------------------- */
std::string ft_st_to_string(size_t x)
{
	std::ostringstream oss;

	oss << x;
	return (oss.str());
}

/* --------------------------------------------------------------------------------
Create a new environment in vector form, which includes all the values of the
environment in which webserv is running + custom values related to the request
currently being processed
-------------------------------------------------------------------------------- */
void new_env(char** envp, Request& req, std::vector<std::string>& my_env, Server* serv)
{
	size_t i = 0;
	while (envp[i])
		my_env.push_back(envp[i++]);
	my_env.push_back("CONTENT_TYPE=" + req.get_header()["Content-Type"]);
	my_env.push_back("GATEWAY_INTERFACE=CGI/1.1");

	char path[124] = {0};
	my_env.push_back("PATH_TRANSLATED=" + std::string(getcwd(path, 124)));
	if (!req.get_query().empty())
		my_env.push_back("QUERY_STRING=" + req.get_query());
	if (!req.get_method().empty())
		my_env.push_back("REQUEST_METHOD=" + req.get_method());
	if (req.get_len())
		my_env.push_back("CONTENT_LENGTH=" + ft_st_to_string(req.get_len()));
	if (!req.get_protocol().empty())
		my_env.push_back("SERVER_SOFTWARE=" + req.get_protocol());

	my_env.push_back("SERVER_NAME=" + serv->get_name());
	my_env.push_back("HTTP_ACCEPT=" + req.get_header()["Accept"]);
	my_env.push_back("HTTP_ACCEPT_LANGUAGE=" + req.get_header()["Accept-Language"]);
	my_env.push_back("HTTP_USER_AGENT=" + req.get_header()["User-Agent"]);
	my_env.push_back("SCRIPT_NAME=" + req.get_url());
	my_env.push_back("HTTP_REFERER=" + req.get_header()["Referer"]);
}

/* --------------------------------------------------------------------------------
Transform the vector created in the new_env() function into a char* array
-------------------------------------------------------------------------------- */
char**	vector_to_tab(std::vector<std::string>& vec)
{
	char** tab;
	int i = 0;

	tab = (char**)malloc(sizeof(char*)* (vec.size() + 1));
	if (!tab)
	{
		perror("malloc vector_to_tab");
		exit(1);
	}

	std::cout << colors::grey << colors::on_yellow << "--- ENV ---" << colors::reset << colors::yellow << std::endl;

	for (std::vector<std::string>::iterator it = vec.begin(); it != vec.end(); it++)
	{
		tab[i++] = (char*)(*it).c_str();
		std::cout << tab[i - 1] << std::endl;
	}

	std::cout << colors::reset;

	tab[i] = 0;
	return tab;
}

/* --------------------------------------------------------------------------------
Looks very much like microshell or pipex: many lines to simply execve() a file
with the right executable in the right environment

The text generated by the executable is read and returned at the end of the
function
-------------------------------------------------------------------------------- */
std::string exec_CGI(std::string filePath, char** envp, Request& req, Server* serv)
{
	std::cout << colors::bright_magenta << "filePath: " << colors::reset << filePath << std::endl;
	std::string execPath = search_exec(filePath);

	std::cout << colors::bright_magenta << "execPath: " << colors::reset << execPath << std::endl;
	if (execPath == "")
	{
		std::cerr << "Bad file" << std::endl;
		return ("");
	}

	// int		fdIn = 0;
	// int		fd_in[2];
	int		fd_out[2];
	char*	tab[3];
	std::vector<std::string> env;
	pid_t	pid;
	char	buff[BUFFER_SIZE + 1] = {0};
	std::string	ret = "";
	int		i;

	new_env(envp, req, env, serv);
	char** myEnv = vector_to_tab(env);

	// pipe(fd_in);
	pipe(fd_out);

	pid = fork();
	if (pid == -1)
	{
		perror("fork()");
		exit(1);
	}
	else if (pid == 0)
	{
		// close(fd_in[1]);
		close(fd_out[0]);
		// if (dup2(fd_in[0], STDIN_FILENO) == -1)
		// {
		// 	perror("dup2");
		// 	exit(1);
		// }
		if (dup2(fd_out[1], STDOUT_FILENO) == -1)
		{
			perror("dup2");
			exit(1);
		}
		// close(fd_in[0]);
		// close(fd_in[1]);
		close(fd_out[0]);
		close(fd_out[1]);

		tab[0] = (char*)execPath.c_str();
		tab[1] = (char*)filePath.c_str();
		tab[2] = NULL;

		execve(tab[0], tab, myEnv);
		perror("execve");
		exit(1);
	}
	else
	{
		// fdIn = dup(0);
		// if (fdIn == -1)
		// {
		// 	perror("dup");
		// 	exit(1);
		// }
		// if (dup2(fd_in[0], 0) == -1)
		// {
			// perror("dup2");
			// exit(1);
		// }
		// if (!req.get_full_body().empty())
			// write(fd_in[1], req.get_full_body().c_str(), req.get_len());
		// close(fd_in[0]);
		// close(fd_in[1]);
		waitpid(pid, NULL, 0);
		// if (dup2(fd_in[0], STDIN_FILENO) == -1)
		// {
		// 	perror("dup2");
		// 	exit(1);
		// }
		close(fd_out[1]);
		free(myEnv);
		i = read(fd_out[0], buff, BUFFER_SIZE);
		if (i == -1)
		{
			perror("read");
			exit(1);
		}
		buff[i] = '\0';
		ret += std::string(buff);
		while (i > 0)
		{
			i = read(fd_out[0], buff, BUFFER_SIZE);
			if (i == -1)
			{
				perror("read");
				exit(1);
			}
			buff[i] = '\0';
			ret += std::string(buff);
		}
		close(fd_out[0]);
		return ret;
	}
	return "";
}
